export const toppingData = [
  {
    id:1,
    src:'../../img/toppings/anchovy.svg',
    title:'anchovy'
  },{
    id:2,
    src:'../../img/toppings/bacon.svg',
    title:'bacon'
  },{
    id:3,
    src:'../../img/toppings/basil.svg',
    title:'basil'
  },{
    id:4,
    src:'../../img/toppings/chili.svg',
    title:'chili'
  },{
    id:5,
    src:'../../img/toppings/mozzarella.svg',
    title:'mozzarella'
  },{
    id:6,
    src:'../../img/toppings/mushroom.svg',
    title:'mushroom'
  },{
    id:7,
    src:'../../img/toppings/olive.svg',
    title:'olive'
  },{
    id:8,
    src:'../../img/toppings/onion.svg',
    title:'onion'
  },{
    id:9,
    src:'../../img/toppings/pepper.svg',
    title:'pepper'
  },{
    id:10,
    src:'../../img/toppings/pepperoni.svg',
    title:'pepperoni'
  },{
    id:11,
    src:'../../img/toppings/prawn.svg',
    title:'prawn'
  },{
    id:12,
    src:'../../img/toppings/sweetcorn.svg',
    title:'sweetcorn'
  },{
    id:13,
    src:'../../img/toppings/tomato.svg',
    title:'tomato'
  },
];

